### ISSUE TITLE
Default value for Options not returned

### ISSUE THREAD

**Issue by pierlo-upitup** [wp-cli/php-cli-tools#30]
Setting a default for an option doesn't really seem to do much (besides showing the default value in the help screen:

```
$arguments->addOption( array('name', 'n'), 
    array(
        'description' => 'Set the name",
        'default' => 'Foo Bar'
    )
));
```

Doing this:

```
echo $arguments['name']
```

returns nothing, but it should return "Foo Bar" unless the default has been overridden.

**Comment by rantonmattei** [comment]
PR https://github.com/wp-cli/php-cli-tools/pull/79 is out for this bug.

**Comment by rantonmattei** [comment]
@danielbachhuber what's the expected behavior here?
Following the example above, my fix (https://github.com/wp-cli/php-cli-tools/pull/79) populates the default if the option was specified with no value. I.e.
```sh
php my_script.php --name
```
will populate `name` with "Foo Bar"

However with
```sh
php my_script.php
```
No default value will populate `name`

Maybe for the latter, it would make sense to populate the default as well. 

Let me know what you guys think.
Thanks

**Comment by danielbachhuber** [comment]
I'm open to your lead. I'm new to maintaining this project, so I'm learning about the internals as we go along.

**Comment by danielbachhuber** [comment]
> Is this ever going to be fixed?

As soon as someone submits a pull request for it.
